apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /home/muhab/Desktop/data/postgres 
  persistentVolumeReclaimPolicy: Retain
