apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: java-crud-app
type: Opaque
data:
  postgres-db: d2ViYXBw  # webapp (base64)
  postgres-user: ZGJhZG1pbg==  # dbadmin (base64)
  postgres-password: Q2hhbmdlTWUxMjMh  # ChangeMe123! (base64)